In [1]:
import numpy as np 

one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [2]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)


[[ 6  5]
 [11  7]
 [ 4  8]]


In [3]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [7]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[57 61 94 71 67 50]


In [8]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.78198056 0.09107162 0.8998478  0.63335357 0.18942772 0.16281686]


In [9]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.78198056 2.09107162 2.8998478  2.63335357 2.18942772 2.16281686]


In [10]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[171 183 282 213 201 150]


In [13]:
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [24]:
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)

[ 1.19523544 -0.93241722 -1.60013111 -1.7335118  -1.92933548 -1.22767756
  0.29404444 -0.5106586   0.17562319 -1.07291213 -0.63578201  1.55728278
  1.15925989  0.27646904  0.99566685]
[19.99493029 20.13404163 25.29066254 26.54140312 29.63459777 36.33826323
 37.04223847 43.27302224 44.29087038 44.08126926 50.80244032 50.44146235
 55.84657319 57.30150377 59.97851081]
